import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from '../context/AuthContext';
import { CartProvider } from '../context/CartContext';
import Navbar from '../components/Navbar';
import MobileNavbar from '../components/MobileNavbar';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased relative min-h-screen overflow-x-hidden`}
      >
        {/* Global background gradient and glow */}
        <div className="fixed inset-0 -z-10 bg-gradient-to-br from-[#10111a] via-[#181c24] to-[#0a0a0a]" />
        <div className="fixed left-1/2 top-1/3 -translate-x-1/2 -translate-y-1/2 w-[900px] h-[600px] bg-gradient-radial from-blue-700/40 via-purple-600/30 to-transparent rounded-full blur-3xl opacity-70 -z-10" />
        <AuthProvider>
          <CartProvider>
            <div className="hidden sm:block"><Navbar /></div>
            <div className="sm:hidden"><MobileNavbar pageName="Konoha Shop" /></div>
            {children}
          </CartProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
